// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3566.MuleDrivingBeforeMaine;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController muleTankDriveSpeedController1;
    public static SpeedController muleTankDriveSpeedController2;
    public static SpeedController muleTankDriveSpeedController3;
    public static SpeedController muleTankDriveSpeedController4;
    
    public static RobotDrive muleTankDriveRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        muleTankDriveSpeedController1 = new Jaguar(1, 1);
	LiveWindow.addActuator("MuleTankDrive", "Speed Controller 1", (Jaguar) muleTankDriveSpeedController1);
        
        muleTankDriveSpeedController2 = new Jaguar(1, 2);
	LiveWindow.addActuator("MuleTankDrive", "Speed Controller 2", (Jaguar) muleTankDriveSpeedController2);
        
        muleTankDriveSpeedController3 = new Jaguar(1,3);
        muleTankDriveSpeedController4 = new Jaguar(1,4);
        
        
        muleTankDriveRobotDrive21 = new RobotDrive(muleTankDriveSpeedController1, muleTankDriveSpeedController2,muleTankDriveSpeedController3,muleTankDriveSpeedController4);
        
	
        muleTankDriveRobotDrive21.setSafetyEnabled(false);
        muleTankDriveRobotDrive21.setExpiration(0.1);
        muleTankDriveRobotDrive21.setSensitivity(0.5);
        muleTankDriveRobotDrive21.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
