// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3566.MuleDrivingBeforeMaine.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3566.MuleDrivingBeforeMaine.Robot;
/**
 *
 */
public class  DriveWithJoySticks extends Command {
    public DriveWithJoySticks() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.muleTankDrive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        
        System.out.println("Joystick1 is " + Robot.oi.xBox.getRawAxis(1));
      Robot.muleTankDrive.muleDriveTank(Robot.oi.xBox.getRawAxis(1), Robot.oi.xBox.getRawAxis(4),Robot.oi.xBox.getRawAxis(2),Robot.oi.xBox.getRawAxis(5));
        // 1 X, 2X, 1Y, 2Y
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
