// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3566.MuleDrivingBeforeMaine.subsystems;
import org.usfirst.frc3566.MuleDrivingBeforeMaine.RobotMap;
import org.usfirst.frc3566.MuleDrivingBeforeMaine.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class MuleTankDrive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController1 = RobotMap.muleTankDriveSpeedController1;
    SpeedController speedController2 = RobotMap.muleTankDriveSpeedController2;
    SpeedController speedController3 = RobotMap.muleTankDriveSpeedController3;
    SpeedController speedController4 = RobotMap.muleTankDriveSpeedController4;
    RobotDrive robotDrive21 = RobotMap.muleTankDriveRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        setDefaultCommand(new DriveWithJoySticks());
    }
    
    
    public void muleDriveTank(double x, double y, double rotation, double gyroAngle){
        robotDrive21.mecanumDrive_Cartesian(x, y, rotation, gyroAngle);
    }
   
}
